In [16]:
import pandas as pd
import sqlite3
con = sqlite3.connect("C:/Users/sahwa/OneDrive/Documents/OJT SEM3/ipl-cricket-analytics/data/raw/ipl.db")
def q(sql):
    return pd.read_sql(sql,con)

In [17]:
q('''
SELECT bowler_type
from deliveries;
''')

             bowler_type
0       Right arm Medium
1       Right arm Medium
2       Right arm Medium
3       Right arm Medium
4       Right arm Medium
...                  ...
288221    Right arm Fast
288222    Right arm Fast
288223    Right arm Fast
288224  Right arm Medium
288225  Right arm Medium

[288226 rows x 1 columns]

In [18]:
q('''
SELECT bowler_type, LENGTH(bowler_type) AS value_length,
COUNT(*) AS count
FROM deliveries
GROUP BY bowler_type
ORDER BY value_length
LIMIT 5;''')

      bowler_type  value_length  count
0             NaN           NaN    339
1                           1.0      8
2        Legbreak           8.0  13893
3   Left arm Fast          13.0   3727
4  Right arm Fast          14.0  42126

In [19]:
q('''
SELECT bowler_type,LENGTH(bowler_type)AS old_length,NULLIF(TRIM(bowler_type),'')AS bowler_type_clean
from deliveries
where TRIM(bowler_type)='';''')

  bowler_type  old_length bowler_type_clean
0                       1              None
1                       1              None
2                       1              None
3                       1              None
4                       1              None
5                       1              None
6                       1              None
7                       1              None

In [20]:
q('''
SELECT COUNT(*)AS whitespace_only
FROM
(SELECT NULLIF(TRIM(bowler_type),'')AS bowler_type FROM deliveries)
WHERE bowler_type IS NOT NULL AND TRIM(bowler_type)='';
''')

   whitespace_only
0                0

In [21]:
q('''
SELECT COUNT(*)AS unknown_bowler_type
FROM deliveries
WHERE NULLIF(TRIM(bowler_type),'')IS NULL;
''')

   unknown_bowler_type
0                  347

In [22]:
q('''
SELECT  DISTINCT bowler_type FROM deliveries; ''')

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [23]:
q("""SELECT toss_decision,CASE WHEN toss_decision='bat' THEN 'Batting First' 
WHEN toss_decision='field' THEN 'Fielding First' 
ELSE toss_decision END AS toss_decision_clean,
COUNT(*) AS n
FROM matches
GROUP BY toss_decision;"""
)

  toss_decision toss_decision_clean    n
0           bat       Batting First  412
1         field      Fielding First  800

In [24]:
q('''SELECT bowler_type, COUNT(*) AS count
FROM deliveries
GROUP BY bowler_type
ORDER BY bowler_type;''')

                                       bowler_type  count
0                                              NaN    339
1                                                       8
2                                    Left arm Fast   3727
3                             Left arm Fast medium  15376
4                                  Left arm Medium   8778
5                             Left arm Medium fast  13495
6                              Left arm Wrist spin   4279
7                                         Legbreak  13893
8                                  Legbreak Googly  22670
9                                   Right arm Fast  42126
10                           Right arm Fast Medium     73
11                           Right arm Fast medium  31154
12                                Right arm Medium  49776
13                           Right arm Medium fast  20897
14            Right arm Medium, Right arm Offbreak    652
15  Right arm Medium, Right arm Offbreak, Legbreak    223
16                              Right arm Offbreak  30791
17                    Right arm Offbreak, Legbreak    448
18             Right arm Offbreak, Legbreak Googly     61
19      Right arm Offbreak, Slow Left arm Orthodox     42
20                          Slow Left arm Orthodox  29128
21     Slow Left arm Orthodox, Left arm Wrist spin    290

In [25]:
q('''
SELECT bowler_type,CASE WHEN bowler_type='Right arm Fast Medium' THEN 'Right arm fast medium' ELSE bowler_type END AS bowler_type
FROM deliveries;''')

             bowler_type       bowler_type
0       Right arm Medium  Right arm Medium
1       Right arm Medium  Right arm Medium
2       Right arm Medium  Right arm Medium
3       Right arm Medium  Right arm Medium
4       Right arm Medium  Right arm Medium
...                  ...               ...
288221    Right arm Fast    Right arm Fast
288222    Right arm Fast    Right arm Fast
288223    Right arm Fast    Right arm Fast
288224  Right arm Medium  Right arm Medium
288225  Right arm Medium  Right arm Medium

[288226 rows x 2 columns]

In [26]:
q('''
SELECT CASE WHEN NULLIF(TRIM(bowler_type),'')='Right arm Fast Medium' THEN 'Right arm Fast Medium'
ELSE NULLIF(TRIM(bowler_type),'')
END AS bowler_type_clean
FROM deliveries; ''')

       bowler_type_clean
0       Right arm Medium
1       Right arm Medium
2       Right arm Medium
3       Right arm Medium
4       Right arm Medium
...                  ...
288221    Right arm Fast
288222    Right arm Fast
288223    Right arm Fast
288224  Right arm Medium
288225  Right arm Medium

[288226 rows x 1 columns]

In [27]:
q('''
SELECT COUNT (DISTINCT( bowler_type))
FROM deliveries;
''')

   COUNT (DISTINCT( bowler_type))
0                              21

In [28]:
q('''
SELECT COUNT(DISTINCT
CASE WHEN NULLIF(TRIM(bowler_type),'')='Right arm Fast Medium' THEN 'Right arm Fast medium'
ELSE NULLIF(TRIM(bowler_type),'')END)
AS cleaned_count
FROM deliveries; 
''')

   cleaned_count
0             19

In [29]:
q('''
SELECT team_name,
(SELECT COUNT (*)FROM matches m
WHERE m.team1=t.team_name OR m.team2=t.team_name)AS played
FROM teams t
ORDER BY played;
''')

                      team_name  played
0               Deccan Chargers       0
1       Rising Pune Supergiants       0
2          Kochi Tuskers Kerala      14
3        Rising Pune Supergiant      30
4                 Gujarat Lions      30
5                 Pune Warriors      46
6          Lucknow Super Giants      66
7                Gujarat Titans      69
8              Rajasthan Royals     245
9           Chennai Super Kings     260
10        Kolkata Knight Riders     272
11                 Punjab Kings     272
12               Delhi Capitals     276
13  Royal Challengers Bangalore     279
14          Sunrisers Hyderabad     280
15               Mumbai Indians     285

In [30]:
q('''
SELECT team_name,
CASE WHEN team_name = 'Rising Pune Supergiants' THEN 'Rising Pune Supergiant'
ELSE team_name END as t
FROM teams;
''')

                      team_name                            t
0   Royal Challengers Bangalore  Royal Challengers Bangalore
1           Sunrisers Hyderabad          Sunrisers Hyderabad
2                Mumbai Indians               Mumbai Indians
3        Rising Pune Supergiant       Rising Pune Supergiant
4                 Gujarat Lions                Gujarat Lions
5         Kolkata Knight Riders        Kolkata Knight Riders
6           Chennai Super Kings          Chennai Super Kings
7              Rajasthan Royals             Rajasthan Royals
8                Delhi Capitals               Delhi Capitals
9                  Punjab Kings                 Punjab Kings
10         Lucknow Super Giants         Lucknow Super Giants
11               Gujarat Titans               Gujarat Titans
12              Deccan Chargers              Deccan Chargers
13         Kochi Tuskers Kerala         Kochi Tuskers Kerala
14                Pune Warriors                Pune Warriors
15      Rising Pune Supergiants       Rising Pune Supergiant

In [31]:
q('''
SELECT INSTR('Wankhede Stadium,Mumbai',',');''')

   INSTR('Wankhede Stadium,Mumbai',',')
0                                    17

In [32]:
q("""
SELECT SUBSTR('Wankhede Stadium,Mumbai',1,17-1) AS extract;""")

            extract
0  Wankhede Stadium

In [33]:
q('''
SELECT DISTINCT venue
FROM matches; ''')

                                                venue
0                               M Chinnaswamy Stadium
1           Rajiv Gandhi International Stadium, Uppal
2             Maharashtra Cricket Association Stadium
3              Saurashtra Cricket Association Stadium
4                              Holkar Cricket Stadium
5                               M.Chinnaswamy Stadium
6                                    Wankhede Stadium
7                                        Eden Gardens
8                                    Feroz Shah Kotla
9   Punjab Cricket Association IS Bindra Stadium, ...
10                                         Green Park
11       Punjab Cricket Association IS Bindra Stadium
12                 Rajiv Gandhi International Stadium
13                             MA Chidambaram Stadium
14                             Sawai Mansingh Stadium
15                               Arun Jaitley Stadium
16  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
17                               Sheikh Zayed Stadium
18                Dubai International Cricket Stadium
19                            Sharjah Cricket Stadium
20           MA Chidambaram Stadium, Chepauk, Chennai
21                           Wankhede Stadium, Mumbai
22                   Narendra Modi Stadium, Ahmedabad
23                        Arun Jaitley Stadium, Delhi
24                   Zayed Cricket Stadium, Abu Dhabi
25                          Brabourne Stadium, Mumbai
26                 Dr DY Patil Sports Academy, Mumbai
27      Maharashtra Cricket Association Stadium, Pune
28                              Eden Gardens, Kolkata
29  Punjab Cricket Association IS Bindra Stadium, ...
30  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
31  Rajiv Gandhi International Stadium, Uppal, Hyd...
32                   M Chinnaswamy Stadium, Bengaluru
33                Barsapara Cricket Stadium, Guwahati
34                     Sawai Mansingh Stadium, Jaipur
35  Himachal Pradesh Cricket Association Stadium, ...
36  Maharaja Yadavindra Singh International Cricke...
37  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
38         Punjab Cricket Association Stadium, Mohali
39                    MA Chidambaram Stadium, Chepauk
40                         Dr DY Patil Sports Academy
41                                           Newlands
42                                   St George's Park
43                                          Kingsmead
44                                    SuperSport Park
45                                       Buffalo Park
46                              New Wanderers Stadium
47                              De Beers Diamond Oval
48                                    OUTsurance Oval
49                                  Brabourne Stadium
50                       Sardar Patel Stadium, Motera
51                                   Barabati Stadium
52       Vidarbha Cricket Association Stadium, Jamtha
53       Himachal Pradesh Cricket Association Stadium
54                                      Nehru Stadium
55                         Subrata Roy Sahara Stadium
56   Shaheed Veer Narayan Singh International Stadium
57                 JSCA International Stadium Complex
58  Maharaja Yadavindra Singh International Cricke...

In [34]:
q('''
SELECT COUNT(DISTINCT TRIM(SUBSTR(venue,1,
CASE WHEN INSTR(venue,',') > 0
THEN INSTR(venue,',')-1 ELSE LENGTH(venue)END))) AS after_rule
FROM matches;
''')

   after_rule
0          42

In [35]:
q('''
SELECT DISTINCT TRIM(SUBSTR(venue,1,
CASE WHEN INSTR(venue,',') > 0
THEN INSTR(venue,',')-1 ELSE LENGTH(venue)END)) AS venue_clean
FROM matches
ORDER BY venue_clean;
''')

                                          venue_clean
0                                Arun Jaitley Stadium
1                                    Barabati Stadium
2                           Barsapara Cricket Stadium
3   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
4                                   Brabourne Stadium
5                                        Buffalo Park
6                               De Beers Diamond Oval
7                          Dr DY Patil Sports Academy
8   Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
9                 Dubai International Cricket Stadium
10                                       Eden Gardens
11                                   Feroz Shah Kotla
12                                         Green Park
13       Himachal Pradesh Cricket Association Stadium
14                             Holkar Cricket Stadium
15                 JSCA International Stadium Complex
16                                          Kingsmead
17                              M Chinnaswamy Stadium
18                              M.Chinnaswamy Stadium
19                             MA Chidambaram Stadium
20  Maharaja Yadavindra Singh International Cricke...
21            Maharashtra Cricket Association Stadium
22                              Narendra Modi Stadium
23                                      Nehru Stadium
24                              New Wanderers Stadium
25                                           Newlands
26                                    OUTsurance Oval
27       Punjab Cricket Association IS Bindra Stadium
28                 Punjab Cricket Association Stadium
29                 Rajiv Gandhi International Stadium
30                               Sardar Patel Stadium
31             Saurashtra Cricket Association Stadium
32                             Sawai Mansingh Stadium
33   Shaheed Veer Narayan Singh International Stadium
34                            Sharjah Cricket Stadium
35                               Sheikh Zayed Stadium
36                                   St George's Park
37                         Subrata Roy Sahara Stadium
38                                    SuperSport Park
39               Vidarbha Cricket Association Stadium
40                                   Wankhede Stadium
41                              Zayed Cricket Stadium

In [36]:
q('''
SELECT COALESCE (NULL,'unknown');''')

  COALESCE (NULL,'unknown')
0                   unknown

In [37]:
q('''
SELECT city,COALESCE(city,'unknown') AS city_clean
FROM matches
WHERE city IS NULL
LIMIT 10;''')

   city city_clean
0  None    unknown
1  None    unknown
2  None    unknown
3  None    unknown
4  None    unknown
5  None    unknown
6  None    unknown
7  None    unknown
8  None    unknown
9  None    unknown

In [38]:
q('''
SELECT COUNT(*)
FROM matches 
WHERE COALESCE(city,'unknown')='unknown';''')

   COUNT(*)
0        51

In [39]:
q('''
SELECT CAST('2019' AS INTEGER);''')

   CAST('2019' AS INTEGER)
0                     2019

In [40]:
q('''
SELECT DISTINCT season,
SUBSTR(season,1,4)AS first_four,
CAST(SUBSTR(season,1,4)AS INTEGER)AS season_year
FROM matches
ORDER BY season_year;
''')

     season first_four  season_year
0      2008       2008         2008
1      2009       2009         2009
2      2010       2010         2010
3      2011       2011         2011
4      2012       2012         2012
5      2013       2013         2013
6      2014       2014         2014
7      2015       2015         2015
8      2016       2016         2016
9      2017       2017         2017
10     2018       2018         2018
11     2019       2019         2019
12  2020/21       2020         2020
13     2021       2021         2021
14     2022       2022         2022
15     2023       2023         2023
16     2024       2024         2024
17     2025       2025         2025
18     2026       2026         2026

In [44]:
q('''
SELECT COUNT(DISTINCT CAST(SUBSTR(season,1,4)AS integer))AS season_year
fROM matches;''')

   season_year
0           19

In [42]:
q('''
SELECT venue,count(*)
OVER(PARTITION BY venue)
from venues;
''')

,venue,count(*)\nOVER(PARTITION BY venue)
0,Arun Jaitley Stadium,1
1,"Arun Jaitley Stadium, Delhi",1
2,Barabati Stadium,1
3,"Barsapara Cricket Stadium, Guwahati",1
4,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1
...,...,...
58,SuperSport Park,1
59,"Vidarbha Cricket Association Stadium, Jamtha",1
60,Wankhede Stadium,1
61,"Wankhede Stadium, Mumbai",1
62,"Zayed Cricket Stadium, Abu Dhabi",1

In [43]:
q("""
SELECT venue_id, venue,
ROW_NUMBER() OVER(PARTITION BY venue ORDER BY venue_id) AS RN
FROM venues;
""")

    venue_id                                              venue  RN
0         16                               Arun Jaitley Stadium   1
1         24                        Arun Jaitley Stadium, Delhi   1
2         55                                   Barabati Stadium   1
3         37                Barsapara Cricket Stadium, Guwahati   1
4         34  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   1
..       ...                                                ...  ..
58        48                                    SuperSport Park   1
59        56       Vidarbha Cricket Association Stadium, Jamtha   1
60         7                                   Wankhede Stadium   1
61        22                           Wankhede Stadium, Mumbai   1
62        25                   Zayed Cricket Stadium, Abu Dhabi   1

[63 rows x 3 columns]

In [46]:
q('''
WITH ranked as(
select venue_id,venue,
row_number()over(partition by venue order by venue_id)as rn
from venues)
select count(*) as kept
from ranked
where rn = 1;
''')

   kept
0    59

In [47]:
con.executescript('''
drop view if exists v_matches_clean;
create view v_matches_clean as
SELECT *,
CASE WHEN venue_comma_clean = 'M. Chinnaswamy stadium'
then 'M.Chinnaswamy Stadium'
else venue_comma_clean
end as venue_clean
from(select * ,
trim(substr(venue,1,
case when instr(venue,',')>0
then instr(vene,',')-1
else length (venue)end))as venue_comma_clean
from matches)''')
con.commit()